---
title: "explore"
author: "Sophia Zheng"
date: "12/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

read_clean <- function(path) {
  return (read_csv(
    path,
    col_types = cols(.default = col_double(),
                     city = col_character(),
                     state = col_character(),
                     metro = col_character(),
                     date = col_date(format = "%Y-%m-%d"))))
}

zhvi <- read_clean("clean-data/zhvi.csv")
sale_prices <- read_clean("clean-data/sale_prices.csv")
zri <- read_clean("clean-data/zri.csv")
rental_prices <- read_clean("clean-data/rental_prices.csv")
median_income <- read_clean("clean-data/median_income.csv")
```

```{r cache=TRUE}
all_housing_data <-
  left_join(zhvi, 
            sale_prices, 
            by = c("region_id", "zip_code", "date")) %>% 
  full_join(zri, 
            by = c("region_id", 
                   "zip_code", 
                   "city", 
                   "state", 
                   "metro", 
                   "county_name", 
                   "date")) %>%
  full_join(rental_prices, 
            by = c("zip_code", 
                   "city", 
                   "state", 
                   "metro", 
                   "county_name", 
                   "date"))

mean_housing_data <- all_housing_data %>%
  group_by(metro, date) %>%
  summarize(
    mean_zhvi = mean(zhvi, na.rm = TRUE),
    mean_sale_price = mean(sale_price, na.rm = TRUE),
    mean_zri = mean(zri, na.rm = TRUE),
    mean_rental_price = mean(rental_price, na.rm = TRUE)
  ) %>% 
  full_join(median_income, by = c("metro", "date")) %>% 
  pivot_longer(cols = c(mean_zhvi, 
                        mean_sale_price, 
                        mean_zri, 
                        mean_rental_price, 
                        median_income),
               names_to = "value_type",
               values_to = "mean_value")
```

```{r}
mean_housing_data %>% 
  write_csv(path = "housing-explorations-app/all_housing_data.csv")
```

