---
title: "Housing Explorations"
author: "Sophia Zheng"
date: "11/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(fs)
library(zoo)
library(janitor)
library(tidyverse)
```

```{r cache = TRUE}
# get data
dir_create("raw-data")
download.file(url = "http://files.zillowstatic.com/research/public/Zip/Zip_Zhvi_AllHomes.csv",
              destfile = "raw-data/zhvi.csv")
download.file(url = "http://files.zillowstatic.com/research/public/Zip/Sale_Prices_Zip.csv",
              destfile = "raw-data/sale_prices.csv")
download.file(url = "http://files.zillowstatic.com/research/public/Zip/Zip_Zri_AllHomesPlusMultifamily.csv",
              destfile = "raw-data/zri.csv")
download.file(url = "http://files.zillowstatic.com/research/public/Zip/Zip_MedianRentalPrice_AllHomes.csv",
              destfile = "raw-data/rental_prices.csv")
download.file(url = "http://files.zillowstatic.com/research/public/Affordability_Income_2018Q4.csv",
              destfile = "raw-data/median_income.csv")

zhvi <- read_csv("raw-data/zhvi.csv",
                 col_types = cols(
                              .default = col_double(),
                              RegionName = col_character(),
                              City = col_character(),
                              State = col_character(),
                              Metro = col_character(),
                              CountyName = col_character()
                            ))

sale_prices <- read_csv("raw-data/sale_prices.csv",
                        col_types = cols(
                                      .default = col_double(),
                                      RegionName = col_character(),
                                      StateName = col_character()
                                    )) %>% 
  select(- StateName)

zri <- read_csv("raw-data/zri.csv",
                col_types = cols(
                              .default = col_double(),
                              RegionName = col_character(),
                              City = col_character(),
                              State = col_character(),
                              Metro = col_character(),
                              CountyName = col_character()
                            ))

rental_prices <- read_csv("raw-data/rental_prices.csv",
                          col_types = cols(
                                        .default = col_double(),
                                        RegionName = col_character(),
                                        City = col_character(),
                                        State = col_character(),
                                        Metro = col_character(),
                                        CountyName = col_character()
                                      ))

median_income <- read_csv("raw-data/median_income.csv",
                   col_types = cols(
                                .default = col_double(),
                                RegionName = col_character()
                              ))
dir_delete("raw-data")
```

```{r cache = TRUE}
clean <- function(df, values_to) {
  x <- df %>%
    pivot_longer(cols = contains("-"),
                 names_to = "date",
                 values_to = values_to) %>%
    drop_na() %>% 
    clean_names() %>%
    rename(zip_code = region_name) %>%
    select(-size_rank)
  
  x$date <- as.Date(as.yearmon(x$date))
  
  return (x)
}

clean_zhvi <- clean(zhvi, "zhvi") %>% 
  filter(metro %in% c("New York-Newark-Jersey City", 
                      "San Francisco-Oakland-Hayward", 
                      "Seattle-Tacoma-Bellevue"))

clean_sale_prices <- clean(sale_prices, "sale_price")

clean_zri <- clean(zri, "zri") %>% 
  filter(metro %in% c("New York-Newark-Jersey City",
                      "San Francisco-Oakland-Hayward",
                      "Seattle-Tacoma-Bellevue"))

clean_rental_prices <- clean(rental_prices, "rental_price") %>% 
  filter(metro %in% c("New York-Newark-Jersey City",
                      "San Francisco-Oakland-Hayward",
                      "Seattle-Tacoma-Bellevue"))

clean_median_income <- median_income %>%
  pivot_longer(cols = contains("-"),
               names_to = "date",
               values_to = "median_income") %>%
  filter(str_detect(RegionName, "New York|San Francisco|Seattle")) %>%
  separate(RegionName, into = c("city", "state"), sep = ", ") %>%
  clean_names() %>% 
  mutate(metro = case_when(city == "New York" ~ "New York-Newark-Jersey City", 
                           city == "San Francisco" ~ "San Francisco-Oakland-Hayward", 
                           city == "Seattle" ~ "Seattle-Tacoma-Bellevue"))

clean_median_income$date <- as.Date(as.yearmon(clean_median_income$date))
```

```{r}
dir_create("clean-data")

clean_zhvi %>% 
  write_csv(path = "clean-data/zhvi.csv")

clean_sale_prices %>% 
  write_csv(path = "clean-data/sale_prices.csv")

clean_zri%>% 
  write_csv(path = "clean-data/zri.csv")

clean_rental_prices %>% 
  write_csv(path = "clean-data/rental_prices.csv")

clean_median_income %>% 
  write_csv(path = "clean-data/median_income.csv")
```


